//go:build !ignore_autogenerated

package models

import (
	"fmt"

	"github.com/azhai/goent"
	"github.com/azhai/goent/drivers/sqlite"
	"github.com/azhai/goent/utils"
)

// Database is the database connection with its driver.
type Database struct {
	DefaultSchema
	*goent.DB
}

var db *Database

// GetDB returns the database connection
func GetDB() *Database {
	return db
}

// InitDB opens a database connection and auto-migrates the schema
func InitDB(dbPath, logFile string) (*Database, error) {
	_ = utils.MakeDirForFile(dbPath)
	drv := sqlite.OpenDSN(dbPath)
	ent, err := goent.Open[Database](drv, logFile)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}

	if err = goent.AutoMigrate(ent); err != nil {
		return nil, fmt.Errorf("failed to migrate database: %w", err)
	}

	db = ent
	return ent, nil
}

// CloseDB closes the database connection
func CloseDB() error {
	if db != nil {
		return goent.Close(db)
	}
	return nil
}
