// Code generated by goent-gen. DO NOT EDIT.
//
//go:build !ignore_autogenerated

package models

import "github.com/azhai/goent"

// GetID implements goent.Entity interface
func (t *Wallpaper) GetID() int64 {
	return t.ID
}

// SetID implements goent.Entity interface
func (t *Wallpaper) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields
func (t *Wallpaper) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "guid", Value: t.GUID},
		{Key: "date", Value: t.Date},
		{Key: "slug", Value: t.Slug},
		{Key: "title", Value: t.Title},
		{Key: "headline", Value: t.Headline},
		{Key: "copyright", Value: t.Copyright},
		{Key: "description", Value: t.Description},
		{Key: "image_dpi", Value: t.ImageDPI},
		{Key: "file_size", Value: t.FileSize},
	}
}

// ScanDest returns a slice of pointers to Wallpaper fields for database scanning
func (t *Wallpaper) ScanDest() []any {
	return []any{
		&t.ID,
		&t.GUID,
		&t.Date,
		&t.Slug,
		&t.Title,
		&t.Headline,
		&t.Copyright,
		&t.Description,
		&t.ImageDPI,
		&t.FileSize,
	}
}

// FetchWallpaper creates a FetchFunc for Wallpaper
func FetchWallpaper() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Wallpaper).ScanDest()
	}
}
