//go:build !ignore_autogenerated

package models

import (
	"github.com/azhai/goent"
)

// PublicSchema contains all table definitions
type PublicSchema struct {
	Wallpaper *goent.Table[Wallpaper]
}

// Wallpaper represents the wallpapers table
type Wallpaper struct {
	ID          int64   `goe:"pk"`                                // Primary key, auto increment
	GUID        string  `json:"guid" goe:"column:guid"`           // Unique identifier
	Date        string  `json:"date" goe:"unique"`                // Date, unique
	Slug        string  `json:"slug"`                             // Image ID without OHR. prefix and resolution
	Title       string  `json:"title"`                            // Title
	Headline    string  `json:"headline"`                         // Headline
	Copyright   string  `json:"copyright"`                        // Copyright
	Description *string `json:"description"`                      // Description
	ImageDPI    string  `json:"image_dpi" goe:"column:image_dpi"` // Resolution, e.g. "1920x1080"
	FileSize    int64   `json:"file_size" goe:"default:0"`        // File size in KB
}

// TableName returns the database table name
func (*Wallpaper) TableName() string {
	return "t_wallpapers"
}
